models/contact.py
from utils.db import db

class Contact(db.Model):
    __tablename__ = 'contact'
    
    id = db.Column(db.Integer, primary_key=True) 
    fullname = db.Column(db.String(96), nullable=False)
    email = db.Column(db.String(96), nullable=False, unique=True)
    phone = db.Column(db.String(15), nullable=True)
    
    # Definimos el constructor del modelo
    def __init__(self, fullname: str, email: str, phone: str = None):
        self.fullname = fullname
        self.email = email
        self.phone = phone

routes/contacts.py
from flask import Blueprint, render_template, request, flash, redirect, get_flashed_messages
from services.contact_service import ContactService;
from helpers.transform_error import handle_errors

contacts = Blueprint("contacts", __name__)


@contacts.route("/", methods=["GET"])
def home():
    all_contacts = ContactService.findAll()
    return render_template("index.html", contact = all_contacts)


@contacts.route("/new", methods=["GET", "POST"])
def add_contact():
    if request.method == "POST":
        
        data = {
            "fullname": request.form.get("fullname"),
            "email": request.form.get("email"),
            "phone": request.form.get("phone")
        }

        try:
            ContactService.create(data)
            flash("Contacto creado exitosamente.")
            return redirect("/")
        except ValueError as ve:
            errors = handle_errors(ve)
            for category, message in errors:
                flash(message, category=category)
        except Exception as e:
            flash(f"Error al agregar contacto: {str(e)}") 
    
    errors = get_flashed_messages(with_categories=True)
    return render_template('register.html', errors=errors)


@contacts.route('/update/<int:id>', methods=['GET', 'POST'])
def update_contact(id):
    if request.method == 'GET':
        contact = ContactService.findOneById(id)
        if not contact:
            return "Contacto no encontrado", 404
        return render_template('update.html', data = contact)
    
    if request.method == 'POST':
        fullname = request.form['fullname']
        email = request.form['email'],
        phone = request.form['phone']
        
        updated_contact = ContactService.update_contact(id, fullname, email, phone)
        if updated_contact:
            return redirect('/')
        else:
            return "Error al actualizar el contacto", 400
        
@contacts.route('/delete/<int:id>', methods=['GET'])
def delete_contact(id):
        ContactService.delete_contact(id)
        return redirect('/')

@contacts.route('/about<int:id>', methods=['GET'])
def about_contact(id):
    contact = ContactService.findOneById(id)
    
    return render_template('about.html', data = contact)

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Correo: {{data.email}}</li>
        <li>Numero de telefono: {{data.phone}}</li>
        <li>Nombre: {{data.fullname}}</li>
    </ul>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>

    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>
<body class="bg-gray-900 text-white">
    <div class="container mx-auto p-6">

        <a href="/new" class="text-blue-500 hover:underline mr-4 mb-3 hover:ease-in duration-300">Agregar Nuevo contacto</a>
        <div class="overflow-x-auto flex justify-center items-center">
            <table class="min-w-full text-left text-sm">

                <thead class="bg-gray-800">
                    <tr>
                        <th class="px-6 py-3 font-bold text-gray-300">ID</th>
                        <th class="px-6 py-3 font-bold text-gray-300">Nombre</th>
                        <th class="px-6 py-3 font-bold text-gray-300">Email</th>
                        <th class="px-6 py-3 font-bold text-gray-300">Phone</th>
                        <th class="px-6 py-3 font-bold text-gray-300">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-gray-700 divide-y divide-gray-600">

                    {% if contact %}
                    {% for c in contact %}
                    <tr>
                        <td class="px-6 py-4">{{c.id}}</td>
                        <td class="px-6 py-4">{{c.fullname}}</td>
                        <td class="px-6 py-4">{{c.email}}</td>
                        <td class="px-6 py-4">{{c.phone}}</td>
                        <td class="px-6 py-4">
                            <a href="{{ url_for('contacts.update_contact', id=c.id) }}" class="text-blue-500 hover:underline mr-4">Update</a>
                            <a href="{{ url_for('contacts.delete_contact', id=c.id) }}" class="text-red-500 hover:underline mr-4">Delete</a>
                            <a href="{{ url_for('contacts.about_contact', id=c.id) }}" class="text-green-500 hover:underline mr-4">About</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

</head>
<body class="bg-gray-900 text-white">


    <div class="container mx-auto p-6">
        <div class="max-w-lg mx-auto bg-gray-800 p-8 rounded-lg shadow-lg">
            <h1 class="text-2xl font-bold mb-6 text-center">Registrar contacto</h1>
           
            <form action="/new" method="post">
                <div class="mb-4">
                    <label for="fullname" class="block text-gray-300 font-bold mb-2">Nombre </label>
                    <input type="text" name="fullname" placeholder="Ingrese su nombre" class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    {% for category, message in errors %}
                        {% if category == 'fullname' %}
                            <span class="error" style="color: red;">{{ message }}</span>
                        {% endif %}
                    {% endfor %}
                </div>

                <div>
                    <label for="email" class="block text-gray-300 font-bold mb-2">Correo</label>
                    <input type="text" name="email" placeholder="Ingrese su email" class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    {% for category, message in errors %}
                        {% if category == 'email' %}
                            <span class="error" style="color: red;">{{ message }}</span>
                            {% elif category == 'duplicate_email' %}
                            <span class="error" style="color: red;">{{ message }}</span>
                        {% endif %}
                    {% endfor %}
            
                </div>
                <div>
                    <label for="phone" class="block text-gray-300 font-bold mb-2">Teléfono</label>
                    <input type="text" name="phone" placeholder="Ingrese su teléfono" class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    {% for category, message in errors %}
                        {% if category == 'phone' %}
                            <span class="error" style="color: red;">{{ message }}</span>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="text-center mt-3">
                    <button type="submit" class="px-6 py-2 bg-blue-500 text-white font-bold rounded-md hover:bg-blue-600 transition duration-300">Enviar</button>
                </div>
            </form>
        </div>
    </div> 
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

</head>
<body class="bg-gray-900 text-white">

    <div class="container mx-auto p-6">
        <div class="max-w-lg mx-auto bg-gray-800 p-8 rounded-lg shadow-lg">
            <h1 class="text-2xl font-bold mb-6 text-center">Actualizar contacto</h1>
            <form method="POST" action="{{ url_for('contacts.update_contact', id=data.id) }}">
                <div class="mb-4">
                    <label for="fullname" class="block text-gray-300 font-bold mb-2">Nombre:</label>
                    <input type="text" id="fullname" name="fullname" value="{{ data.fullname }}" required class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>

                <div class="mb-4">
                    <label for="fullname" class="block text-gray-300 font-bold mb-2">Correo:</label>
                    <input  type="email" id="email" name="email" value="{{ data.email }}" required class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                
                <div class="mb-4">
                    <label for="fullname" class="block text-gray-300 font-bold mb-2">Teléfono:</label>
                    <input  type="text" id="phone" name="phone" value="{{ data.phone }}" required class="w-full px-4 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>

                <div class="text-center">
                    <button type="submit" class="px-6 py-2 bg-blue-500 text-white font-bold rounded-md hover:bg-blue-600 transition duration-300">Enviar</button>
                </div>
            </form>            
        </div>
    </div>    
</body>
</html>